// <auto-generated />
using System;
using FootballFormation.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FootballFormation.Core.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260322223040_AddGameScoreAndGoals")]
    partial class AddGameScoreAndGoals
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("FootballFormation.Core.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("FormationType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GameDurationMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Opponent")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ScoreAway")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ScoreHome")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SplitType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UnavailablePlayerIds")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("FootballFormation.Core.Models.GameGoal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AssisterId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsOwnGoal")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Minute")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ScorerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AssisterId");

                    b.HasIndex("GameId");

                    b.HasIndex("ScorerId");

                    b.ToTable("GameGoals");
                });

            modelBuilder.Entity("FootballFormation.Core.Models.GamePeriod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FormationTypeOverride")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PeriodType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("GamePeriods");
                });

            modelBuilder.Entity("FootballFormation.Core.Models.GamePlayerPosition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GamePeriodId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSubstitute")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GamePeriodId");

                    b.HasIndex("PlayerId");

                    b.ToTable("GamePlayerPositions");
                });

            modelBuilder.Entity("FootballFormation.Core.Models.MatchPreferences", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DefaultFormation")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DefaultSplitType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GameDurationMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MatchDay")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("MatchPreferences");
                });

            modelBuilder.Entity("FootballFormation.Core.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AlternativePositions")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("PreferredPosition")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ShirtNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Surname")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("FootballFormation.Core.Models.GameGoal", b =>
                {
                    b.HasOne("FootballFormation.Core.Models.Player", "Assister")
                        .WithMany()
                        .HasForeignKey("AssisterId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FootballFormation.Core.Models.Game", "Game")
                        .WithMany("Goals")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FootballFormation.Core.Models.Player", "Scorer")
                        .WithMany()
                        .HasForeignKey("ScorerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assister");

                    b.Navigation("Game");

                    b.Navigation("Scorer");
                });

            modelBuilder.Entity("FootballFormation.Core.Models.GamePeriod", b =>
                {
                    b.HasOne("FootballFormation.Core.Models.Game", "Game")
                        .WithMany("Periods")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("FootballFormation.Core.Models.GamePlayerPosition", b =>
                {
                    b.HasOne("FootballFormation.Core.Models.GamePeriod", "GamePeriod")
                        .WithMany("PlayerPositions")
                        .HasForeignKey("GamePeriodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FootballFormation.Core.Models.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GamePeriod");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("FootballFormation.Core.Models.Game", b =>
                {
                    b.Navigation("Goals");

                    b.Navigation("Periods");
                });

            modelBuilder.Entity("FootballFormation.Core.Models.GamePeriod", b =>
                {
                    b.Navigation("PlayerPositions");
                });
#pragma warning restore 612, 618
        }
    }
}
