// <auto-generated />
using System;
using FootballFormation.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FootballFormation.Core.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260903191239_AddMatchDayDetails")]
    partial class AddMatchDayDetails
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("FootballFormation.Core.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int?>("TeamId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("FootballFormation.Core.Models.Club", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ThemeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Clubs");
                });

            modelBuilder.Entity("FootballFormation.Core.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AbsencesRecorded")
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("ClockAccumulatedSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ClockRunningSince")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("DressingRoom")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("DressingRoomDuty")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("FieldName")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("FlagDuty")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("FormationType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GameDurationMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GuestPlayerIds")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InjuredPlayerIds")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsHomeGame")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LivePeriodId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MatchState")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MatchType")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan?>("MeetTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Opponent")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ScoreAway")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ScoreHome")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SeasonId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SplitType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SportsPark")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("UnavailablePlayerIds")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan?>("WarmUpTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("WashDuty")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SeasonId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("FootballFormation.Core.Models.GameComment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AuthorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EditedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("GameId", "CreatedAt");

                    b.ToTable("GameComments");
                });

            modelBuilder.Entity("FootballFormation.Core.Models.GameGoal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AssisterId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AtSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("GamePeriodId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsOpponentGoal")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsOwnGoal")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Minute")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ScorerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AssisterId");

                    b.HasIndex("GameId");

                    b.HasIndex("GamePeriodId");

                    b.HasIndex("ScorerId");

                    b.ToTable("GameGoals");
                });

            modelBuilder.Entity("FootballFormation.Core.Models.GameInjury", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AtSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GamePeriodId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SlotIndex")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GamePeriodId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("GameId", "PlayerId")
                        .IsUnique();

                    b.ToTable("GameInjuries");
                });

            modelBuilder.Entity("FootballFormation.Core.Models.GamePeriod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EndedAtSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FormationTypeOverride")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PeriodType")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("StartedAtSeconds")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("GamePeriods");
                });

            modelBuilder.Entity("FootballFormation.Core.Models.GamePlayerPosition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GamePeriodId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSubstitute")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SlotIndex")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("GamePeriodId", "PlayerId")
                        .IsUnique();

                    b.ToTable("GamePlayerPositions");
                });

            modelBuilder.Entity("FootballFormation.Core.Models.GameSubstitution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AtSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GamePeriodId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayerOffId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayerOnId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SlotIndex")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("GamePeriodId");

                    b.HasIndex("PlayerOffId");

                    b.HasIndex("PlayerOnId");

                    b.ToTable("GameSubstitutions");
                });

            modelBuilder.Entity("FootballFormation.Core.Models.MatchPreferences", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DefaultFormation")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DefaultSplitType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("FirstTrainingDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("GameDurationMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastTrainingDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("MatchDay")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SeasonId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TrainingDays")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SeasonId")
                        .IsUnique();

                    b.ToTable("MatchPreferences");
                });

            modelBuilder.Entity("FootballFormation.Core.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AlternativePositions")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PreferredPosition")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ShirtNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Surname")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("FootballFormation.Core.Models.Season", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StartDate")
                        .IsUnique();

                    b.ToTable("Seasons");
                });

            modelBuilder.Entity("FootballFormation.Core.Models.SeasonSquadMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsGuest")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsInjured")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SeasonId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("SeasonId", "PlayerId")
                        .IsUnique();

                    b.ToTable("SeasonSquadMembers");
                });

            modelBuilder.Entity("FootballFormation.Core.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClubId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClubId", "Name")
                        .IsUnique();

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("FootballFormation.Core.Models.Training", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<bool>("DidNotTakePlace")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("FromSchedule")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("SeasonId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UnavailablePlayerIds")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SeasonId");

                    b.ToTable("Trainings");
                });

            modelBuilder.Entity("FootballFormation.Core.Models.AppUser", b =>
                {
                    b.HasOne("FootballFormation.Core.Models.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("FootballFormation.Core.Models.Game", b =>
                {
                    b.HasOne("FootballFormation.Core.Models.Season", "Season")
                        .WithMany("Games")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Season");
                });

            modelBuilder.Entity("FootballFormation.Core.Models.GameComment", b =>
                {
                    b.HasOne("FootballFormation.Core.Models.AppUser", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FootballFormation.Core.Models.Game", "Game")
                        .WithMany("Comments")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Game");
                });

            modelBuilder.Entity("FootballFormation.Core.Models.GameGoal", b =>
                {
                    b.HasOne("FootballFormation.Core.Models.Player", "Assister")
                        .WithMany()
                        .HasForeignKey("AssisterId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FootballFormation.Core.Models.Game", "Game")
                        .WithMany("Goals")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FootballFormation.Core.Models.GamePeriod", null)
                        .WithMany()
                        .HasForeignKey("GamePeriodId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("FootballFormation.Core.Models.Player", "Scorer")
                        .WithMany()
                        .HasForeignKey("ScorerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Assister");

                    b.Navigation("Game");

                    b.Navigation("Scorer");
                });

            modelBuilder.Entity("FootballFormation.Core.Models.GameInjury", b =>
                {
                    b.HasOne("FootballFormation.Core.Models.Game", null)
                        .WithMany("Injuries")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FootballFormation.Core.Models.GamePeriod", null)
                        .WithMany()
                        .HasForeignKey("GamePeriodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FootballFormation.Core.Models.Player", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FootballFormation.Core.Models.GamePeriod", b =>
                {
                    b.HasOne("FootballFormation.Core.Models.Game", "Game")
                        .WithMany("Periods")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("FootballFormation.Core.Models.GamePlayerPosition", b =>
                {
                    b.HasOne("FootballFormation.Core.Models.GamePeriod", "GamePeriod")
                        .WithMany("PlayerPositions")
                        .HasForeignKey("GamePeriodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FootballFormation.Core.Models.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GamePeriod");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("FootballFormation.Core.Models.GameSubstitution", b =>
                {
                    b.HasOne("FootballFormation.Core.Models.Game", "Game")
                        .WithMany("Substitutions")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FootballFormation.Core.Models.GamePeriod", "GamePeriod")
                        .WithMany()
                        .HasForeignKey("GamePeriodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FootballFormation.Core.Models.Player", "PlayerOff")
                        .WithMany()
                        .HasForeignKey("PlayerOffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FootballFormation.Core.Models.Player", "PlayerOn")
                        .WithMany()
                        .HasForeignKey("PlayerOnId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("GamePeriod");

                    b.Navigation("PlayerOff");

                    b.Navigation("PlayerOn");
                });

            modelBuilder.Entity("FootballFormation.Core.Models.MatchPreferences", b =>
                {
                    b.HasOne("FootballFormation.Core.Models.Season", "Season")
                        .WithMany()
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Season");
                });

            modelBuilder.Entity("FootballFormation.Core.Models.SeasonSquadMember", b =>
                {
                    b.HasOne("FootballFormation.Core.Models.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FootballFormation.Core.Models.Season", "Season")
                        .WithMany("SquadMembers")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Season");
                });

            modelBuilder.Entity("FootballFormation.Core.Models.Team", b =>
                {
                    b.HasOne("FootballFormation.Core.Models.Club", "Club")
                        .WithMany("Teams")
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Club");
                });

            modelBuilder.Entity("FootballFormation.Core.Models.Training", b =>
                {
                    b.HasOne("FootballFormation.Core.Models.Season", null)
                        .WithMany()
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FootballFormation.Core.Models.Club", b =>
                {
                    b.Navigation("Teams");
                });

            modelBuilder.Entity("FootballFormation.Core.Models.Game", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Goals");

                    b.Navigation("Injuries");

                    b.Navigation("Periods");

                    b.Navigation("Substitutions");
                });

            modelBuilder.Entity("FootballFormation.Core.Models.GamePeriod", b =>
                {
                    b.Navigation("PlayerPositions");
                });

            modelBuilder.Entity("FootballFormation.Core.Models.Season", b =>
                {
                    b.Navigation("Games");

                    b.Navigation("SquadMembers");
                });
#pragma warning restore 612, 618
        }
    }
}
