<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
    <PublishReadyToRun>true</PublishReadyToRun>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\FootballFormation.Core\FootballFormation.Core.csproj" />
    <ProjectReference Include="..\FootballFormation.UI\FootballFormation.UI.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
    <PackageReference Include="MudBlazor" />
    <PackageReference Include="Serilog.AspNetCore" />
  </ItemGroup>

</Project>
